apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: quorum
# kubectl explain rmq.spec
spec:
  # https://hub.docker.com/_/rabbitmq?tab=tags
  image: rabbitmq:3.8.9-management
  replicas: 3
  resources:
    limits:
      memory: 8G
      cpu: 4
    requests:
      memory: 8G
      cpu: 4
  rabbitmq:
    additionalConfig: |
      # https://www.rabbitmq.com/configure.html
      vm_memory_high_watermark.absolute = 7G
      vm_memory_high_watermark_paging_ratio = 0.99

      # https://www.rabbitmq.com/prometheus.html#metric-aggregation
      prometheus.return_per_object_metrics = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quorum-rabbitmq-perf-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quorum-rabbitmq-perf-test
  template:
    metadata:
      labels:
        app: quorum-rabbitmq-perf-test
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: perftest
        # https://hub.docker.com/r/pivotalrabbitmq/perf-test/tags
        image: pivotalrabbitmq/perf-test:2.12.0
        resources:
          limits:
            cpu: 2
            memory: 2G
          requests:
            cpu: 1
            memory: 1G
        command:
          - /bin/bash
          - -c
        args:
          - |-
            bin/runjava com.rabbitmq.perf.PerfTest \
              --uri "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_SERVICE:5672/%2f"
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: quorum-rabbitmq-default-user
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: quorum-rabbitmq-default-user
              key: password
        - name: RABBITMQ_SERVICE
          value: quorum-rabbitmq-client

        - name: PRODUCERS
          value: "100"
        - name: VARIABLE_RATE
          value: "1:30,10:30,2:30,0:60"
        - name: CONFIRM
          value: "1"
        - name: JSON_BODY
          value: "true"
        - name: SIZE
          value: "1000"
        - name: FLAG
          value: "persistent"
        - name: ROUTING_KEY
          value: "quorum"

        - name: CONSUMERS
          value: "200"
        - name: CONSUMER_LATENCY
          value: "50000"

        - name: QUEUE_PATTERN
          value: "quorum-%d"
        - name: QUEUE_PATTERN_FROM
          value: "1"
        - name: QUEUE_PATTERN_TO
          value: "100"
        - name: QUEUE_ARGS
          value: "x-max-length=1000,x-queue-type=quorum,x-max-in-memory-bytes=10000000"
        - name: AUTO_DELETE
          value: "false"

        - name: METRICS_PROMETHEUS
          value: "true"
