{
 "title": "RabbitMQ-PerfTest",
 "description": "RabbitMQ message latency & throughput across all PerfTest instances",
 "tags": [
  "rabbitmq-perf-test",
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "PerfTest Instance",
    "query": "label_values(perftest_published, instance)"
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "label_values(perftest_latency_seconds, quantile)"
   }
  ]
 },
 "panels": [
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "End-to-end message latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "perftest_latency_seconds{quantile=\"$percentile\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end message latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "perftest_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "End-to-end message latency distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "perftest_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"} > 0"
    }
   ]
  },
  {
   "title": "End-to-end message latency distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "perftest_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Publish confirm latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "perftest_confirm_latency_seconds{quantile=\"$percentile\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Publish confirm latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "perftest_confirm_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Publish confirm latency distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "perftest_confirm_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"} > 0"
    }
   ]
  },
  {
   "title": "Publish confirm latency distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "perftest_confirm_latency_seconds{quantile=\"$percentile\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "THROUGHPUT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Messages published / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "targets": [
    { "expr": "perftest_published", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages published / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perftest_published{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages consumed / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perftest_consumed{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages consumed / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "targets": [
    { "expr": "perftest_consumed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages confirmed / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    { "expr": "perftest_confirmed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages confirmed / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perftest_confirmed{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages rejected / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perftest_nacked{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages rejected / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "targets": [
    { "expr": "perftest_nacked", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages returned / s",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "targets": [
    { "expr": "perftest_returned", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Messages returned / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "perftest_returned{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}